### ISSUE TITLE
Parameters Mod

### ISSUE THREAD

**Issue by benzoll37** [ZoinkCN/CS2-TrafficUnlocker#1]
Hello. Interesting mod.
Mod parameters by default are the vanilla parameters?

It would be good to have a reset button of mod parameters.

**Comment by iKatt** [comment]
Great suggestion, +1.

For reference:

- Traffic Reduction: 4
- Work Probability: 20
- School Probability: 20
- Leisure Probability: 20

**Comment by ZoinkCN** [comment]
Good suggestion.
Update soon.

**Comment by ZoinkCN** [comment]
Already updated
